spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: postgres
    password: postgres
    hikari:
      schema: news_schema
  data:
    mongodb:
      uri: 'mongodb://test:test@localhost:27017/administration?authSource=admin'