services:
  mongodb:
    image: "mongo:4.4"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "mongo"
      MONGO_INITDB_DATABASE: "mongo_db"
  postgres:
    image: "postgres:15.0"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres_db"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
  redis:
    image: "redis:7.0.12"
    ports:
      - "6379:6379"