spring:
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/mongo_db?authSource=admin
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres_db
#    username: postgres
#    password: postgres
#    hikari:
#      schema: webflux_schema
#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/postgres_db
#    schema: webflux_schema
#    username: postgres
#    password: postgres
  serverPort: 8789


jjwt:
  password:
    encoder:
      secret: "AllKeysMustBeEncoded_Forever"
      iteration: 64
      keyLength: 256
  secret: 2161ab7861c44c2dae4ca9e2683d071d
  expiration: 3000
  issuer: security