spring:
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/mongo_db?authSource=admin
    redis:
      host: localhost
      port: "6379"

app:
  jwt:
    secret: "secretKeyAlreadyNeeded"
    tokenExpiration: 10m
    refreshTokenExpiration: 30m

server:
  port: "8183"