spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: postgres
    password: postgres
    hikari:
      schema: news_schema
  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true
    drop-first: true