server:
  port: 5250

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: bookstore_schema
  data:
    redis:
      host: localhost
      port: 6379

app:
  redis:
    enable: true
    cacheNames:
      - ViewAllCache
      - ViewByAuthorCache
      - ViewByCategory
    caches:
      ViewAllCache:
        expiry: 15s
      ViewByAuthorCache:
        expiry: 15s
      ViewByCategory:
        expiry: 15s